title: Critical Perspectives on AI/ML in Musical Interfaces
tagline: A workshop at NIME 2021
email: charles.martin@anu.edu.au
description: >- # this means to ignore newlines until "baseurl:"
  We aim to consolidate current ML-related thought in NIME, and to develop a research network that focuses on future work in ML-enhanced interfaces for musical performance. Notably, this objective diverges from previous NIME research that has focused on technical implementations; rather, we aim to offer a forum for academic discussions on critical and theoretical perspectives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://intelligence-in-musical-interfaces.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cpmpercussion
github_username:  intelligence-in-musical-interfaces

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: zivhub/monophase@main
