# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Critical Perspectives on AI/ML in Musical Interfaces
email: charles.martin@anu.edu.au
description: >- # this means to ignore newlines until "baseurl:"
  We aim to consolidate current ML-related thought in NIME, and to develop a research network that focuses on future work in ML-enhanced interfaces for musical performance. Notably, this objective diverges from previous NIME research that has focused on technical implementations; rather, we aim to offer a forum for academic discussions on critical and theoretical perspectives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://intelligence-in-musical-interfaces.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cpmpercussion
github_username:  intelligence-in-musical-interfaces

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
